name: Build Docker Image

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
    - name: Build the Docker image
      run: docker build .
