name: Build & Publish Docker Image To ECR

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install aws cli
        run: |
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          rm awscliv2.zip

      - name: configure aws cli
        env:
          AWS_ROLE_TO_ASSUME: '${{ secrets.AWS_ROLE_TO_ASSUME }}'
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          AWS_ECR_ACCOUNT_URL: '${{ secrets.AWS_ECR_ACCOUNT_URL }}'
        run: |
          # Get temporary credentials to access resoures available to specific role
          temporaryCredentials=$(
            aws sts assume-role \
              --role-arn "${AWS_ROLE_TO_ASSUME}" \
              --role-session-name "gha-chainlink-builder"
          )

          # Deconstruct json response, extracting aws credentials
          accessKeyID=$(echo $temporaryCredentials | jq .Credentials.AccessKeyId | xargs)
          secretAccessKey=$(echo $temporaryCredentials | jq .Credentials.SecretAccessKey | xargs)
          sessionToken=$(echo $temporaryCredentials | jq .Credentials.SessionToken | xargs)

          # Store aws creds in .aws folder
          aws configure set aws_access_key_id ${accessKeyID}
          aws configure set aws_secret_access_key ${secretAccessKey}
          aws configure set aws_session_token ${sessionToken}

          # Use temporary keys to get account ID
          accountID=$(aws sts get-caller-identity --output text --query 'Account')

          # Store credentials in env vars, allowing subsequent steps to use correct credentials
          echo "::set-env name=AWS_ACCESS_KEY_ID::${accessKeyID}";
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${secretAccessKey}";
          echo "::set-env name=AWS_SESSION_TOKEN::${sessionToken}";
          echo "::set-env name=AWS_ACCOUNT_ID::${accountID}";
          echo "::set-env name=AWS_ECR_ACCOUNT_URL::${accountID}.dkr.ecr.us-west-2.amazonaws.com/builder-cache"

      - name: docker login to ECR
        env:
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          AWS_ECR_ACCOUNT_URL: '${{ secrets.AWS_ECR_ACCOUNT_URL }}'
        run: |
          aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" --profile "default" | docker login --username AWS --password-stdin "${AWS_ECR_ACCOUNT_URL}"

      - name: Build and push docker image
        env:
          AWS_ECR_ACCOUNT_URL: '${{ secrets.AWS_ECR_ACCOUNT_URL }}'
          TAG: '${{ steps.updateCacheFile.outputs.builderVersion }}-${{ steps.getDate.outputs.date }}'
        run: |
          docker tag "smartcontract/builder-cache:${TAG}" "${AWS_ECR_ACCOUNT_URL}:${TAG}"
          docker push "${AWS_ECR_ACCOUNT_URL}:${TAG}"
