name: Build & Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    # TODO: version in and env var
    steps:
      - uses: actions/checkout@v2-beta
      - name: Build and publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: smartcontract/builder:1.0.35
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Fetch AWS temporary credentials
        id: temp-creds
        uses: docker://mowat27/sts-assume-role-action
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          AWS_ASSUME_ROLE_ARN: '${{ secrets.AWS_ROLE_TO_ASSUME }}'
      - name: Push docker image to ECR
        env:
          TAG: ${{ steps.config.outputs.ImageTag }}
          AWS_ACCESS_KEY_ID: ${{ steps.temp-creds.outputs.AccessKeyID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.temp-creds.outputs.SecretAccessKey }}
          AWS_SESSION_TOKEN: ${{ steps.temp-creds.outputs.SessionToken }}
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          AWS_ECR_ACCOUNT_URL: "${{ secrets.AWS_ECR_ACCOUNT_URL }}/builder"
        run: |
          docker build -t "smartcontract/builder:${TAG}" . # TODO REMOVE THIS
          docker tag "smartcontract/builder:${TAG}" "${AWS_ECR_ACCOUNT_URL}:${TAG}"

          aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
          aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
          aws configure set aws_session_token "${AWS_SESSION_TOKEN}"
          aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" --profile "default" | docker login --username AWS --password-stdin "${AWS_ECR_ACCOUNT_URL}"
          docker push "${AWS_ECR_ACCOUNT_URL}:${TAG}"
