name: Build & Publish Docker Image To Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: Build the Docker image
        run: docker build .
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: smartcontract/builder:1.0.35
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: "us-west-2"
          role-to-assume: "${{ secrets.AWS_ROLE_TO_ASSUME }}"
          role-external-id: "${{ secrets.AWS_ROLE_EXTERNAL_ID }}"
          role-duration-seconds: 1200
          role-session-name: "BuilderCacheBuildAndPush"

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to AWS ECR
        env:
          ECR_REGISTRY: "${{ steps.login-ecr.outputs.registry }}"
          ECR_REPOSITORY: "builder-cache"
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:1.0.35
