name: Build & Publish Docker Image To ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kciter/aws-ecr-action@v1
        with:
          access_key_id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          account_id: "${{ secrets.AWS_ACCOUNT_ID }}"
          repo: "795953128386.dkr.ecr.us-west-2.amazonaws.com/builder"
          region: us-west-2
          create_repo: false
          tags: "${{ github.sha }},1.0.35"
          Dockerfile: "./Dockerfile"
